<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <Folder Include="Commands\Base\" />
        <Folder Include="Domain\Models\" />
        <Folder Include="Resource\Fonts\" />
        <Folder Include="Views\Pages\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Injectio" Version="6.1.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resource\Localization\Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\RenderFrame.axaml.cs">
        <DependentUpon>RenderFrame.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

<ItemGroup>
      <ProjectReference Include="..\KirasaEngine.Bulding\KirasaEngine.Bulding.csproj" />
      <ProjectReference Include="..\KirasaEngine.Core\KirasaEngine.Core.csproj" />
      <ProjectReference Include="..\KirasaEngine.MGL\KirasaEngine.MGL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resource\Localization\Resources.en-EN.resx">
        <Generator></Generator>
      </EmbeddedResource>
      <EmbeddedResource Update="Resource\Localization\Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resource\Localization\Resources.ru-RU.resx">
        <Generator></Generator>
      </EmbeddedResource>
    </ItemGroup>
</Project>
