<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Domain\Interfaces\" />
      <Folder Include="Infrastructure\Abstract\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Injectio" Version="6.1.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    </ItemGroup>

</Project>
